# Generated by Django 3.0.8 on 2020-07-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wangyiboBest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='changeImageFile',
            field=models.ImageField(default='', upload_to='changeImg/'),
        ),
    ]
