# Generated by Django 3.0.8 on 2020-07-29 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wangyiboBest', '0002_auto_20200729_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='changeImageFile',
        ),
    ]
