# Generated by Django 3.0.8 on 2020-07-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wangyiboBest', '0003_remove_imagemodel_changeimagefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='changeImageFile',
            field=models.ImageField(default='', upload_to='changeImg/'),
        ),
    ]
